/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Explore;

import processing.core.PApplet;

public class App extends PApplet {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        String[] appArgs = {"Explore Game"};
        App mySketch = new App();
        PApplet.runSketch(appArgs, mySketch);
    }

    public void settings() {
        size(600, 800);
    }

    public void setup() {
        background(255);
        noStroke();
        fill(0);
        textSize(32);
        text("Hello World!", 100, 100);
    }

    public void draw() {
        background(255);
        fill(0);
        textSize(32);
        text("Hello World!", 100, 100);
    }
}
